### ISSUE TITLE
Homework 4 problem 2 typo

### ISSUE THREAD

**Issue by dfpetrin** [hrmacbeth/math2001#13]
<img width="747" alt="Screenshot 2024-04-26 at 19 46 22" src="https://github.com/hrmacbeth/math2001/assets/1427220/8a3f5cfc-0feb-4122-b276-90267ec69a87">

The problem as stated in the Lean homework file is:
```
theorem problem2 {t : ℤ} (h : t ≡ 2 [ZMOD 4]) :
    3 * (t ^ 2 + t - 8) ≡ 3 * (2 ^ 2 + 2 - 8) [ZMOD 4] := by
```
so, 2 substituted for t in all places on the right side.

**Comment by hrmacbeth** [comment]
Thanks! Fixed.
