### ISSUE TITLE
exercises 1.3.11 (10) and (15) not possible using given tactics?

### ISSUE THREAD

**Issue by rzeta0** [hrmacbeth/math2001#15]
I am working through the course and have completed all the exercises in 1.3.11 except (10) and (15).

I don't believe these are possible using the two tactics that have been given to the reader at this point in the course (rw and ring).

None of the given examples or hint/tips/tricks seem to apply.

It is entirely possible I am missing the solution, but after 2 days of trying I suspect the solutions require tactics not yet given to the reader. 

---

Let's consider (10)

```
example {p : ℝ} (h1 : 5 * p - 3 = 3 * p + 1) : p = 2 :=
    sorry

```

No amount of substitution (rw) seems to isolate `p`.

---

Let's consider (15)

```
example {x y : ℝ} (h1 : x + 3 = 5) (h2 : 2 * x - y * x = 0) : y = 2 :=
  sorry

```

The pen and paper solution requires a recognition that (2-y)*x = 0 means either x = 0 or 2-y = 0, or both. But the other hypothesis tells us that x is not 0, and so y must equal 2. 

However none of the given tactics, "rw" and "ring" enable this structure of proof at this point in the course.

Am I wrong?

**Comment by hrmacbeth** [comment]
Hi @rzeta0, glad to hear of your interest in the course.  I assure you, both problems are possible with only `rw` and `ring`! :-).

Problem 15 has been discussed a number of times on the Lean discussion board -- see for example [here](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/exercise.20of.20the.20mechanics.20of.20proof) and [here](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Mechanics.20of.20Proof.201.2E3.2E11.20exercise.2015).  I don't think problem 10 has been discussed yet, but you could start a topic for it.

**Comment by rzeta0** [comment]
Thanks Heather for the pointers.  I wanted to also thank you for your encouraging comment. Too often online maths forums (eg stack exchange) are rather unfriendly to newbies and this can prevent people from progressing in what should be an exciting and noble discipline! So thanks for that :)
