### ISSUE TITLE
Question: How is Lean automatically graded?

### ISSUE THREAD

**Issue by Seasawher** [hrmacbeth/math2001#2]
Nice to meet you．I am learning Lean by reading this material. Thank you for creating nice book!

I have a question about Lean's automated grading.

---

I am thinking of using Lean to organise private maths competitions. However, I'm faced with the problem of how to automate grading.

The [Note for instructors](https://hrmacbeth.github.io/math2001/00_Introduction.html#note-for-instructors) in this material states that Gradescope is used for automatic grading. Could you tell me how to grade Lean code using Gradescope? 

Alternatively, please let me know if you know anything about automatic grading of lean codes, not just Gradescope.

Thank you for reading.

**Comment by hrmacbeth** [comment]
Hello @Seasawher, as you will see from the manifest in the repository, the autograder used is https://github.com/robertylewis/cs22-lean-autograder.  However, to use this autograder you will need a affiliation with an institution which has a subscription to Gradescope.  For other ideas, I recommend asking at the Lean community [discussion board](https://leanprover.zulipchat.com/).
