### ISSUE TITLE
A couple of typos

### ISSUE THREAD

**Issue by zhassan-aws** [hrmacbeth/math2001#4]
1. The solution of Example 2.4.2 starts with "We have that p^2 \le 8 = 3^2". 
![image](https://github.com/hrmacbeth/math2001/assets/88045115/27352e68-bc4f-4f94-95c9-23499e9cebd7)
2. Problem 3 of Exercises 3.1.10 says "Prove that if the integers m and **m** are even, then m + n is odd". It should be "if m is odd and n is even ...".
![image](https://github.com/hrmacbeth/math2001/assets/88045115/57a3199d-53d7-43cd-ae4f-0f13f12eabb4)

**Comment by hrmacbeth** [comment]
Thank you!  Noted for next major revision.

**Comment by hrmacbeth** [comment]
Fixed in fe7386009629bc00a1bcc89065db2db305b0ab63
