### ISSUE TITLE
typeclass instance problem is stuck, it is often due to metavariables

### ISSUE THREAD

**Issue by grindingpeon** [hrmacbeth/math2001#8]
Hello 

Thank you very much for the awesome book!

When filling out the proof of example `4.4.5`, I am getting an error, which I having trouble debugging.
I am trying to apply the theorem `abs_lt_of_sq_lt_sq'` in order to show 
$c < 3 \wedge c > -3$.

The error turns up here:

![image](https://github.com/leanprover/lean4/assets/82541231/151a4577-fb06-4f26-ae62-97e7debd6736)

when I try to use the following theorem:

![image](https://github.com/leanprover/lean4/assets/82541231/39b20282-1f08-4e3d-bee8-bc2d184c9d25)

having these hypotheses:
![image](https://github.com/leanprover/lean4/assets/82541231/36f3639f-d047-40ed-905f-299b739b0db4)

Using my hypotheses `h2` and `h3c` should allow me to conclude the result of the theorem.
However, it seems as if some of the types are making it throw an error.

Could anyone guide me on how to resolve this?

Thank you very much!

**Comment by hrmacbeth** [comment]
This is quite a subtle error!  I'll have to think about whether there's a way to make it give a more useful error message.

The lemma `abs_lt_of_sq_lt_sq'` lets you simplify the expression `c ^ 2 < 3 ^ 2` to `-3 < c < 3` when you are working in a "ring," which is a numeric type which has negation (as well as addition and multiplication).  For example, `ℤ`, `ℚ`, `ℝ` are rings, and negation makes sense in all of these.

But in this problem we are working in `ℕ`, which is not a ring (it does not have negative numbers).  This is actually an easier setting in which to simplify `c ^ 2 < 3 ^ 2` -- it simplifies directly to `c < 3`.  You can do this with the `cancel` tactic:
```lean
cancel 2 at h2
```
